version: "3"

services:
  careific:
    container_name: careific
    # The name of the image that will be created when building this container
    image: careific
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Asia/Jakarta
    restart: unless-stopped
    ports:
      - 3001:3000